### ISSUE TITLE
alot looks to be working, having some issues with database status though

### ISSUE THREAD

**Issue by shoemocker** [philthynz/zabbix-mssql-2008-2012-powershell#1]
hello! i am testing this on our sql servers at work and looks like a lot is working which has me excited. however database up/down status looks to be not working for me.

![image](https://user-images.githubusercontent.com/7282566/67343904-39ca3580-f4fc-11e9-8279-8ef73003d8a3.png)
 
it is pretty much showing that all my databases are down. not exactly sure what to do here.

![image](https://user-images.githubusercontent.com/7282566/67343979-7433d280-f4fc-11e9-8a55-4543156a961b.png)

i believe i have everything set up correctly on the agent side and i fixed the locations on the scripts to match my directory. 

running server 2008r2 with zabbix 4.4 and sql server 2008 it looks like.

any ideas?

**Comment by philthynz** [comment]
Hey.

Under Latest data what is the last value of the DB's?

![image](https://user-images.githubusercontent.com/17504095/67344848-785ffe80-f595-11e9-9a93-ccfc6c42b0ef.png)

You can also try to run the powershell script locally on the server to make sure it's working. `C:\zabbix\scripts\database_status_disc.ps1 -instName 'MSSQLSERVER' -dbName 'DBNAME'`

**Comment by shoemocker** [comment]
i figured it out. it was a herpa derp on my end. i edited the userparameter_mssql on the zabbix agent side but not the template side like mentioned in your article -.- everything is working great now. i changed template to ->

SQL Server, Instance {#INST}, DB {#DBNAME}: Database Status system.run["powershell C:\'Program Files'\'Zabbix Agent'\scripts\database_status_disc.ps1 -instName '{#INST}' -dbName '{#DBNAME}'"]
